### ISSUE TITLE
[miyauchi] デザインデータの作り方の修正

### ISSUE THREAD

**Issue by udky** [tdgyagi/design_study1#1]

**Comment by udky** [comment]
- [ ] レイヤー名を正確に入れる
- [ ] クリッピングマスクでトリミングしない

**Comment by 38chi** [comment]
修正しました。

**Comment by tdgyagi** [comment]
- [ ] ファイル名が間違っていますので、正しい状態にしてください。
- [ ] DSファイルを削除するツールを入れてpushしてください。
